[workspace]
authors = ["Arghya Ranjan Das <arghyaranjandas@gmail.com>"]
channels = ["conda-forge"]
name = "hh-bbtautau-scouting"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11,<3.13"
root = "*"
numpy = "*"
matplotlib = "*"
mplhep = "*"
pyyaml = "*"
xrootd = "*"
pandas = "*"
ipykernel = "*"
seaborn = ">=0.13.2,<0.14"
fpdf2 = ">=2.8.7,<3"

[pypi-dependencies]
brilws = "*"
prettytable = "*"
