"""Example:

How to train the CMS electron MVA ID with xgbo
==============================================


Reading the data
-----------------

Read in the electron ntuple. These are 20000 electron entries generated by
the ElectronMVANtuplizer [1a,1b], converted to HDF 5 for better pandas
compatibility.

"""

import pandas as pd
import numpy as np
import os
import sys
import ROOT
import copy as cp
import uproot
import xgboost2tmva
from collections import OrderedDict
import pickle

from argparse import ArgumentParser

parser = ArgumentParser(description="Training")
parser.add_argument("model", action="store", type=str, default="", help="Model to use for inference")
parser.add_argument("-N", "--numEvents", dest="trainEvents", action="store", type=int, default=30000, help="Number of events to be used for training")
parser.add_argument("-P", "--numPoints", dest="nPoints", action="store", type=int, default=1000, help="Number of points to be tested")
parser.add_argument("-R", "--numRounds", dest="nRounds", action="store", type=int, default=100, help="Number of rounds to train")
parser.add_argument("-o", "--outpath", dest="outputpath", action="store", type=str, default="test", help="The utput path")

options = parser.parse_args()

import datetime, time
ts = time.time()
date = datetime.datetime.fromtimestamp(ts).strftime('%Y_%m_%d__%H_%M_%S')


#from xgbo.xgbo.xgbo import XgboClassifier
#classifier = XgboClassifier(out_dir="./tmp/XGBinference{}".format(date)) #classifier.models["inference"] = pickle.load(open(options.model, "rb"))

classifier = pickle.load(open(options.model, "rb"))


# Loading the data (copy pasted from train.py)
features_save = [("b_D0_pt", "F"), ("b_D0_eta", "F"), ("b_D0_phi", "F"), ("b_D0_vprob", "F"), ("b_D0_fl", "F"), ("b_D0_fsig", "F"),
	("b_Ds_pt", "F"), ("b_Ds_eta", "F"), ("b_Ds_phi", "F"), ("b_Ds_vprob", "F"), ("b_Ds_fl", "F"), ("b_Ds_fsig", "F"), 
	("b_D0_lip", "F"), ("b_D0_lips", "F"), ("b_D0_pvip", "F"), ("b_Ds_lip", "F"), ("b_Ds_lips", "F"), ("b_Ds_pvip", "F"), 
	("b_tau_pt", "F"), ("b_tau_eta", "F"), ("b_tau_phi", "F"), ("b_tau_fl", "F"), ("b_tau_fsig", "F"), ("b_tau_vprob", "F"), 
	("b_tau_lip", "F"), 
	#("b_tau_lips", "F"), 
	("b_tau_pvip", "F"), ("b_tau_pvipsig", "F"), ("b_tau_alpha", "F"), ("b_tau_legacyMaxdr", "F"), 
	("b_tau_pi1pt", "F"), ("b_tau_pi1eta", "F"), ("b_tau_pi1phi", "F"), 
	("b_tau_pi2pt", "F"), ("b_tau_pi2eta", "F"), ("b_tau_pi2phi", "F"), 
	("b_tau_pi3pt", "F"), ("b_tau_pi3eta", "F"), ("b_tau_pi3phi", "F"), ("b_tau_sumdnn", "F"), 
	#("BsDstarTauNu_k_charge", "F"), ("BsDstarTauNu_pi_charge", "F"), ("BsDstarTauNu_spi_charge", "F"), 
	] #("BsDstarTauNu_mu1_vx", "F"), ("BsDstarTauNu_mu1_vy", "F"), ("BsDstarTauNu_tau_pi1_charge", "F"), ("BsDstarTauNu_tau_pi2_charge", "F"), ("BsDstarTauNu_tau_pi3_charge", "F"), ("BsDstarTauNu_mu1_q", "I"), ("BsDstarTauNu_tau_q", "I"), ("BsDstarTauNu_mu1_vz", "F")


features = [item[0] for item in features_save]

fraction = 0.5
splitcut = ""
numLoad = 10000
debug = 1
weighted = False

if(options.trainEvents==0):
	numEventsSignal=None
	numEventsBackground=None
	numEvents=None
else : 
	numEventsSignal=options.trainEvents/fraction
	numEventsBackground=options.trainEvents/fraction
	numEvents=options.trainEvents/fraction
testSize = fraction


numLoad = testSize*options.trainEvents


cut = splitcut

if (weighted): 
	featuresW= cp.copy(features)
	featuresW.append("weight")
else: 
	featuresW = features

# works, selects the columns with those names to make the pd.df 

featuresToLoad = cp.copy(features)
#featuresToLoad.append("BsDstarTauNu_B_q2")


from loadSamples import loadSamples
samples = loadSamples(featuresToLoad, numLoad)


signal = [samples["signal"]]
background = [samples["background"]]


print "Background composition: {}".format(background[0].keys())

dfSig = pd.concat(signal)
dfBkg = pd.concat(background)

if (weighted): 
	if (debug) : print "Signal weights: {}".format(dfSig["weight"])
	if (debug) : print "Background weights: {}".format(dfBkg["weight"])


print "Features: {}: ".format(dfSig.columns)


# Applying selection
if (not cut==""): 
	dfSig = dfSig.query(cut)
	dfBkg = dfBkg.query(cut)
if (debug) : print "Cut: {}:".format(cut) 

#dfBkg = dfBkg.query(bkgcut)

#dfSig = dfSig.query(splitcut)
#dfBkg = dfBkg.query(splitcut)
#print dfBkg.splitTag
#dfSig.drop(['splitTag'], inplace=True, axis=1, errors='ignore')
#dfBkg.drop(['splitTag'], inplace=True, axis=1, errors='ignore')


# Adding flag for signal 
dfSig['y_labels'] = np.ones(dfSig.shape[0])
dfBkg['y_labels'] = np.zeros(dfBkg.shape[0])


# Merging signal and background into a single data frame 
frame = [dfSig, dfBkg]

df = pd.concat(frame)

"""
Next, we need to define our feature columns. Let's include the particle flow
isolation components, and since we are in the endcap, the relative pre-shower
energy.
"""

"""
Our target variable, y, is whether the electron is matched to a true prompt
electron.
"""

#df.eval("y = matchedToGenEle == 1", inplace=True)
#y_labels = np.concatenate( (np.ones(dfSig.shape[0]), np.zeros(dfBkg.shape[0])) )
#if we want a separate array for the labels 

"""
Finally, we will split up the data frame is training and testing samples, while
extracting the features and target variable.
"""
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df[featuresW],
                                                    df['y_labels'],
                                                    random_state=99,
                                                    test_size=testSize)

"""
Let's now to a simple default xgboost training with early stopping. We have to
convert the data to xgboosts DMatrix format first.
"""
import xgboost as xgb

if (weighted): 
	xgtrain = xgb.DMatrix(X_train[features], label=y_train, weight=X_train["weight"])
	xgtest  = xgb.DMatrix(X_test[features] , label=y_test, weight=X_test["weight"])
else: 
	xgtrain = xgb.DMatrix(X_train[features], label=y_train)
	xgtest  = xgb.DMatrix(X_test[features] , label=y_test)


prediction = classifier.predict(xgtest) #prediction = classifier.predict(xgtest, model="inference")

from sklearn import metrics
if (weighted): 
	fpr_default   , tpr_default, _    = metrics.roc_curve(y_test, prediction, pos_label=1, drop_intermediate=False, sample_weight=np.asarray(X_test["weight"], 'd'))
else: 
	fpr_default   , tpr_default, _    = metrics.roc_curve(y_test, prediction, pos_label=1, drop_intermediate=False)

file = ROOT.TFile.Open(options.outputpath+"/plotsinference.root", "RECREATE")
classicXGboost = file.mkdir("classicXGboost")
classicXGboost.cd()
graph = ROOT.TGraph(len(tpr_default), tpr_default, fpr_default)
graph.SetName("bkgEff(sigEff)")
graph.SetMarkerStyle(21)
graph.SetTitle("bkgEff(sigEff)")
graph.GetXaxis().SetTitle("Signal efficiency")
graph.GetYaxis().SetTitle("Background efficiency")
graph.Write()

