"""Example:

How to train the CMS electron MVA ID with xgbo
==============================================


Reading the data
-----------------

Read in the electron ntuple. These are 20000 electron entries generated by
the ElectronMVANtuplizer [1a,1b], converted to HDF 5 for better pandas
compatibility.

"""

import pandas as pd
import numpy as np
import os
import sys
import ROOT
import copy as cp
import uproot
import xgboost2tmva
from collections import OrderedDict

#put os that we can get args as with other BDT scan

#df = pd.read_hdf("../res/electron_data.hdf")

"""
Reading the ROOT file directly is almost equally easy, and you don't even
need to install ROOT! Just use uproot, a very leightweight python package:

>>> import uproot 

>>> tree = uproot.open("../res/electron_data.root")["ntuplizer/tree"]
>>> df = tree.pandas.df(branches=None, entrystop=None)

Setting up the training and testing samples
-------------------------------------------

First, we select the kinematic range for out training. Let's say we want to
train the ID for the endcap region (1.5 < |eta| < 2.5) above p_T > 10 GeV.

Additionally, we do not want to consider electrons from tau decays, which are
encoded with "matchedToGenEle == 2".
"""

def WriteImportanceToFile(filename, standard = None, default = None, optimized = None, importance = 'gain'): 
	with open(filename, "w") as file:
		if not (standard == None): 
			file.write("XGBoost standard:\n")
			for key, value in standard.get_score(importance_type=importance).iteritems(): 
				file.write("{} : {}\n".format(key, value))
			file.write("\n")

		if not (default == None): 
			file.write("XGBO default:\n")
			for key, value in default.get_score(importance_type=importance).iteritems(): 
				file.write("{} : {}\n".format(key, value))
			file.write("\n")

		if not (optimized == None): 
			file.write("XGBO optimized:\n")
			for key, value in optimized.get_score(importance_type=importance).iteritems(): 
				file.write("{} : {}\n".format(key, value))
			file.write("\n")


def WriteVariables(variables, dest): 
	with open(dest+"/Variables.py", "w") as file: 
		file.write("features_save = [\n")
		for item in variables: 
			assert(len(item)==2)
			file.write("\t(\"{}\", \"{}\"),\n".format(item[0], item[1]))
		file.write("]\n")


debug = 1
weighted = False

from argparse import ArgumentParser

parser = ArgumentParser(description="Training")
parser.add_argument("-N", "--numEvents", dest="trainEvents", action="store", type=int, default=30000, help="Number of events to be used for training")
parser.add_argument("-P", "--numPoints", dest="nPoints", action="store", type=int, default=1000, help="Number of points to be tested")
parser.add_argument("-R", "--numRounds", dest="nRounds", action="store", type=int, default=100, help="Number of rounds to train")
parser.add_argument("-o", "--outpath", dest="outputpath", action="store", type=str, default="test", help="The utput path")
parser.add_argument("-v", "--version", dest="version", action="store", type=str, default="v1", help="The version of files to use")

options = parser.parse_args()


fraction = 0.5
splitcut = "" #"splitTag < 6"
#bkgcut = "BsDstarTauNu_B_q2<7"

#creating output directory 
os.system("mkdir -p "+options.outputpath)
os.system("mkdir -p "+options.outputpath+"/models")



# set ranges in xgbo.py 

if(options.trainEvents==0):
	numEventsSignal=None
	numEventsBackground=None
	numEvents=None
else : 
	numEventsSignal=options.trainEvents/fraction
	numEventsBackground=options.trainEvents/fraction
	numEvents=options.trainEvents/fraction
testSize = fraction


numLoad = testSize*options.trainEvents

# Preselection 




from BDTvariables import features_save 


features = [item[0] for item in features_save]


print "Features: {}".format(len(features))
print "To be saved: {}".format(len(features_save))

cut = splitcut

if (weighted): 
	featuresW= cp.copy(features)
	featuresW.append("weight")
else: 
	featuresW = features

# works, selects the columns with those names to make the pd.df 

featuresToLoad = cp.copy(features)
#featuresToLoad.append("BsDstarTauNu_B_q2")


from loadSamples import loadSamples
samples = loadSamples(featuresToLoad, options.version, numLoad)


signal = [samples["signal"]]
background = [samples["background"]]


print "Background composition: {}".format(background[0].keys())

dfSig = pd.concat(signal)
dfBkg = pd.concat(background)

if (weighted): 
	if (debug) : print "Signal weights: {}".format(dfSig["weight"])
	if (debug) : print "Background weights: {}".format(dfBkg["weight"])


print "Features: {}: ".format(dfSig.columns)


# Applying selection
if (not cut==""): 
	dfSig = dfSig.query(cut)
	dfBkg = dfBkg.query(cut)
if (debug) : print "Cut: {}:".format(cut) 

#dfBkg = dfBkg.query(bkgcut)

#dfSig = dfSig.query(splitcut)
#dfBkg = dfBkg.query(splitcut)
#print dfBkg.splitTag
#dfSig.drop(['splitTag'], inplace=True, axis=1, errors='ignore')
#dfBkg.drop(['splitTag'], inplace=True, axis=1, errors='ignore')


# Adding flag for signal 
dfSig['y_labels'] = np.ones(dfSig.shape[0])
dfBkg['y_labels'] = np.zeros(dfBkg.shape[0])


# Merging signal and background into a single data frame 
frame = [dfSig, dfBkg]

df = pd.concat(frame)

"""
Next, we need to define our feature columns. Let's include the particle flow
isolation components, and since we are in the endcap, the relative pre-shower
energy.
"""

"""
Our target variable, y, is whether the electron is matched to a true prompt
electron.
"""

#df.eval("y = matchedToGenEle == 1", inplace=True)
#y_labels = np.concatenate( (np.ones(dfSig.shape[0]), np.zeros(dfBkg.shape[0])) )
#if we want a separate array for the labels 

"""
Finally, we will split up the data frame is training and testing samples, while
extracting the features and target variable.
"""
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df[featuresW],
                                                    df['y_labels'],
                                                    random_state=99,
                                                    test_size=testSize)

"""
Let's now to a simple default xgboost training with early stopping. We have to
convert the data to xgboosts DMatrix format first.
"""
import xgboost as xgb

if (weighted): 
	xgtrain = xgb.DMatrix(X_train[features], label=y_train, weight=X_train["weight"])
	xgtest  = xgb.DMatrix(X_test[features] , label=y_test, weight=X_test["weight"])
else: 
	xgtrain = xgb.DMatrix(X_train[features], label=y_train)
	xgtest  = xgb.DMatrix(X_test[features] , label=y_test)

params = {'eval_metric':'auc',
          'objective'  :'binary:logistic'}  #binary:logitraw
model_default = xgb.train(params, xgtrain, num_boost_round=1000)

"""
Next we try out the xgbo package.
"""
from xgbo.xgbo.xgbo import XgboClassifier

xgbo_classifier = XgboClassifier(out_dir=options.outputpath)

xgbo_classifier.optimize(xgtrain, init_points=options.nPoints, n_iter=options.nRounds, acq='ei')

trainingdefault = xgbo_classifier.fit(xgtrain, model="default")
trainingroptimized = xgbo_classifier.fit(xgtrain, model="optimized")

xgbo_classifier.save_model(features, model="default")
xgbo_classifier.save_model(features, model="optimized")

print "Training results: "
print "xgboost: {}".format(model_default.get_score(importance_type='gain'))
print "default: {}".format(trainingdefault.get_score(importance_type='gain'))
print "optimized: {}".format(trainingroptimized.get_score(importance_type='gain'))

WriteImportanceToFile(options.outputpath+"/featureImprtance.txt", model_default, trainingdefault, trainingroptimized)


"""
Now, let's make predictions with all models we got on the testing sample.
"""
preds_default    = model_default.predict(xgtest)
preds_early_stop = xgbo_classifier.predict(xgtest, model="default")
preds_optimized  = xgbo_classifier.predict(xgtest, model="optimized")

if (debug) : print preds_default

#ROOT.TMVA.Experimental.SaveXGBoost(xgbo_classifier._models["optimized"].get_dump(), "myBDT", "model.root")

#savevars = [(key, item) for key, item in features_save.items()]
#print savevars

# Saving the models
import pickle
pickle.dump(xgbo_classifier._models["optimized"], open(options.outputpath+"/models/model_optimized.pkcl", "wb"))
pickle.dump(xgbo_classifier._models["default"], open(options.outputpath+"/models/model_default.pkcl", "wb"))
pickle.dump(model_default, open(options.outputpath+"/models/model_standard.pkcl", "wb"))


xgboost2tmva.convert_model(xgbo_classifier._models["optimized"].get_dump(), input_variables=features_save,output_xml=options.outputpath+'/model_optimized/xgboost.xml')


WriteVariables(features_save, options.outputpath)




"""
Finally, we want to plot some ROC curves.
"""
#import matplotlib.pyplot as plt
from sklearn import metrics

if (weighted): 
	fpr_default   , tpr_default, _    = metrics.roc_curve(y_test, preds_default, pos_label=1, drop_intermediate=False, sample_weight=np.asarray(X_test["weight"], 'd'))
	fpr_early_stop, tpr_early_stop, _ = metrics.roc_curve(y_test, preds_early_stop, pos_label=1, drop_intermediate=False, sample_weight=np.asarray(X_test["weight"], 'd'))
	fpr_optimized , tpr_optimized, _  = metrics.roc_curve(y_test, preds_optimized, pos_label=1, drop_intermediate=False, sample_weight=np.asarray(X_test["weight"], 'd'))
else: 
	fpr_default   , tpr_default, _    = metrics.roc_curve(y_test, preds_default, pos_label=1, drop_intermediate=False)
	fpr_early_stop, tpr_early_stop, _ = metrics.roc_curve(y_test, preds_early_stop, pos_label=1, drop_intermediate=False)
	fpr_optimized , tpr_optimized, _  = metrics.roc_curve(y_test, preds_optimized, pos_label=1, drop_intermediate=False)

invfpr_default = np.ones(len(fpr_default)) - fpr_default
invfpr_early_stop = np.ones(len(fpr_early_stop)) - fpr_early_stop
invfpr_optimized = np.ones(len(fpr_optimized)) - fpr_optimized


#print fpr_default 
#print len(tpr_default)

"""
plt.figure()
plt.plot(tpr_default, fpr_default, label='default')
plt.plot(tpr_early_stop, fpr_early_stop, label='early stop')
plt.plot(tpr_optimized, fpr_optimized, label='optimized')
plt.title("Electron MVA ID in endcaps for pT > 10 GeV")
plt.xlabel("Signal efficiency")
plt.ylabel("Background efficiency")
plt.xlim(0.75, 1.0)
plt.ylim(0.0, 0.25)
plt.legend(loc='upper left')
plt.savefig("roc_curve.png")
"""

file = ROOT.TFile.Open(options.outputpath+"/plots.root", "RECREATE")
classicXGboost = file.mkdir("classicXGboost")
classicXGboost.cd()
graph = ROOT.TGraph(len(tpr_default), tpr_default, fpr_default)
graph.SetName("bkgEff(sigEff)")
graph.SetMarkerStyle(21)
graph.SetTitle("bkgEff(sigEff)")
graph.GetXaxis().SetTitle("Signal efficiency")
graph.GetYaxis().SetTitle("Background efficiency")
graph.Write()

classicEffat90 = graph.Eval(0.9)
classicEffat80 = graph.Eval(0.8)

graph = ROOT.TGraph(len(tpr_default), fpr_default, tpr_default)
graph.SetName("scikit-like_ROC")
graph.SetMarkerStyle(21)
graph.SetTitle("scikit-like ROC curve")
graph.GetXaxis().SetTitle("Background efficiency")
graph.GetYaxis().SetTitle("Signal efficiency")
graph.Write()

graph = ROOT.TGraph(len(tpr_default), invfpr_default, tpr_default)
graph.SetName("TMVA-like_ROC")
graph.SetMarkerStyle(21)
graph.SetTitle("TMVA-like ROC curve")
graph.GetXaxis().SetTitle("Background efficiency")
graph.GetYaxis().SetTitle("Signal efficiency")
graph.Write()


packageXGbo = file.mkdir("xgboDefault")
packageXGbo.cd()
graph = ROOT.TGraph(len(tpr_early_stop), tpr_early_stop, fpr_early_stop)
graph.SetName("bkgEff(sigEff)")
graph.SetMarkerStyle(21)
graph.SetTitle("bkgEff(sigEff)")
graph.GetXaxis().SetTitle("Signal efficiency")
graph.GetYaxis().SetTitle("Background efficiency")
graph.Write()

xgboEffat90 = graph.Eval(0.9)
xgboEffat80 = graph.Eval(0.8)

graph = ROOT.TGraph(len(tpr_early_stop), fpr_early_stop, tpr_early_stop)
graph.SetName("scikit-like_ROC")
graph.SetMarkerStyle(21)
graph.SetTitle("scikit-like ROC curve")
graph.GetXaxis().SetTitle("Background efficiency")
graph.GetYaxis().SetTitle("Signal efficiency")
graph.Write()

graph = ROOT.TGraph(len(tpr_early_stop), invfpr_early_stop, tpr_early_stop)
graph.SetName("TMVA-like_ROC")
graph.SetMarkerStyle(21)
graph.SetTitle("TMVA-like ROC curve")
graph.GetXaxis().SetTitle("Background efficiency")
graph.GetYaxis().SetTitle("Signal efficiency")
graph.Write()

optimizedEffat90 = graph.Eval(0.9)
optimizedEffat80 = graph.Eval(0.8)

packageXGboOptimized = file.mkdir("xgboOptimized")
packageXGboOptimized.cd()
graph = ROOT.TGraph(len(tpr_optimized), tpr_optimized, fpr_optimized)
graph.SetName("bkgEff(sigEff)")
graph.SetMarkerStyle(21)
graph.SetTitle("bkgEff(sigEff)")
graph.GetXaxis().SetTitle("Signal efficiency")
graph.GetYaxis().SetTitle("Background efficiency")
graph.Write()

graph = ROOT.TGraph(len(tpr_optimized), fpr_optimized, tpr_optimized)
graph.SetName("scikit-like_ROC")
graph.SetMarkerStyle(21)
graph.SetTitle("scikit-like ROC curve")
graph.GetXaxis().SetTitle("Background efficiency")
graph.GetYaxis().SetTitle("Signal efficiency")
graph.Write()

graph = ROOT.TGraph(len(tpr_optimized), invfpr_optimized, tpr_optimized)
graph.SetName("TMVA-like_ROC")
graph.SetMarkerStyle(21)
graph.SetTitle("TMVA-like ROC curve")
graph.GetXaxis().SetTitle("Background efficiency")
graph.GetYaxis().SetTitle("Signal efficiency")
graph.Write()

X_trainSig = X_train[y_train.astype(bool).values]
X_trainBkg = X_train[(np.ones(len(y_train))-y_train).astype(bool).values]

X_testSig = X_test[y_test.astype(bool).values]
X_testBkg = X_test[(np.ones(len(y_test))-y_test).astype(bool).values]
#print X_testBkg.shape

pSigTrain = xgbo_classifier.predict(xgb.DMatrix(X_trainSig[features]), model='optimized')
pBkgTrain = xgbo_classifier.predict(xgb.DMatrix(X_trainBkg[features]), model='optimized')
pSigTest = xgbo_classifier.predict(xgb.DMatrix(X_testSig[features]), model='optimized')
pBkgTest = xgbo_classifier.predict(xgb.DMatrix(X_testBkg[features]), model='optimized')
#Setting range from [0,1] to [-1, 1] 
pSigTrain = -np.ones(len(pSigTrain))+2*pSigTrain
pBkgTrain = -np.ones(len(pBkgTrain))+2*pBkgTrain
pSigTest = -np.ones(len(pSigTest))+2*pSigTest
pBkgTest = -np.ones(len(pBkgTest))+2*pBkgTest
print pSigTrain

dummyweights = np.ones(len(pSigTrain))


file.cd()
histoSignalTrain = ROOT.TH1D("signalTrain", "SignalTrain", 1000, -1., 1.)
if (weighted): 
	histoSignalTrain.FillN( len(pSigTrain)-1, np.asarray(pSigTrain, 'd'), np.asarray(X_trainSig["weight"], 'd'))
else:
	histoSignalTrain.FillN( len(pSigTrain)-1, np.asarray(pSigTrain, 'd'), np.asarray(dummyweights, 'd'))
histoSignalTrain.Write()
histoBackgroundTrain = ROOT.TH1D("backgroundTrain", "BackgroundTrain", 1000, -1., 1.)
if (weighted): 
	histoBackgroundTrain.FillN( len(pBkgTrain)-1, np.asarray(pBkgTrain, 'd'), np.asarray(X_trainBkg["weight"], 'd'))
else: 
	histoBackgroundTrain.FillN( len(pBkgTrain)-1, np.asarray(pBkgTrain, 'd'), np.asarray(dummyweights, 'd'))
histoBackgroundTrain.Write()
histoSignalTest = ROOT.TH1D("signalTest", "SignalTest", 1000, -1., 1.)
if (weighted): 
	histoSignalTest.FillN( len(pSigTest)-1, np.asarray(pSigTest, 'd'), np.asarray(X_testSig["weight"], 'd'))
else: 
	histoSignalTest.FillN( len(pSigTest)-1, np.asarray(pSigTest, 'd'), np.asarray(dummyweights, 'd'))
histoSignalTest.Write()
histoBackgroundTest = ROOT.TH1D("backgroundTest", "BackgroundTest", 1000, -1., 1.)
if (weighted): 
	histoBackgroundTest.FillN( len(pBkgTest)-1, np.asarray(pBkgTest, 'd'), np.asarray(X_testBkg["weight"], 'd'))
else: 
	histoBackgroundTest.FillN( len(pBkgTest)-1, np.asarray(pBkgTest, 'd'), np.asarray(dummyweights, 'd'))
histoBackgroundTest.Write()


file.Close()

if (debug) : print cut 


filetxt = open(options.outputpath+"/results.txt", "w")
filetxt.write("{} {} {} {} {} {}".format(classicEffat90, classicEffat80, xgboEffat90, xgboEffat80, optimizedEffat90, optimizedEffat80))
filetxt.close()

print "\nFinished training! :)"



"""
[1a] https://github.com/cms-sw/cmssw/blob/master/RecoEgamma/ElectronIdentification/python/Training/ElectronMVANtuplizer_cfg.py
[1b] https://github.com/cms-sw/cmssw/blob/master/RecoEgamma/ElectronIdentification/plugins/ElectronMVANtuplizer.cc
"""
